import TitlePage from "@/components/pageComponents/TitlePage";
import { POST } from "../page";
import Link from "next/link";

export function generateMetadata({params}) {
  const post = POST.find((post) => post.slug === params.slug);
  return {
    title: post.title,
    description: post.title + " - Blog - Generated by create next app",
  };
};

const Slug = ({ params }) => {
  
  const post = POST.find((post) => post.slug === params.slug);

  return (
    <>
        <TitlePage title={post.title} />
        <p className="text-center text-3xl p-4 mb-5">{post.content}</p>
        <div className="text-center">
          <Link
            className="bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded-xl"
            href="/blog"
          >
            Volver
          </Link>
        </div>
    </>
  )
};
export default Slug;