export const metadata = {
  title: "Shop layout",
  description: "Shop - Generated by craete next app",
};

import TitlePage from "@/components/pageComponents/TitlePage";

const Id = ({ params }) => {
    console.log(params)
  return (
    <>
        <TitlePage title="Id" />
        <h1 className="text-center text-3xl">{params.id}</h1>
    </>
  )
};
export default Id;