import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Marketing Layout",
  description: "Generated by create next app",
};

const MarketingLayout = ({children}) => {
  return (
    <>
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <p>Marketing Layout</p>
        {children}
      </body>
      </html>
    </>
  )
};
export default MarketingLayout;