export const metadata = {
  title: "Blog layout",
  description: "Blog - Generated by create next app",
};


import TitlePage from "@/components/pageComponents/TitlePage";
import Link from "next/link";

export const POST = [
  {
    id: 1,
    title: "Post 1",
    slug: "post-1",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 2,
    title: "Post 2",
    slug: "post-2",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
  {
    id: 3,
    title: "Post 3",
    slug: "post-3",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  },
];

const Blog = () => {
  return (
    <>
      <TitlePage />
      <main className="container mx-auto">
        <div className="grid gap-5 p-6">
          {
            POST.map((post) => (
              <div key={post.id} className="bg-white shadow rounded-md p-5">
                <h2 className="text-2xl font-bold">{post.title}</h2>
                <Link href={`/blog/${post.slug}`}>Más información...</Link>
              </div>
            ))
          }
        </div>
        <div className="text-center">
          <a className="text-2xl hover:bg-indigo-400 bg-indigo-300 py-2 px-4 rounded-2xl" href="/perfil">
            Ir a perfil
          </a>
        </div>
      </main>
    </>
  )
};
export default Blog;