import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin layout",
  description: "Generated by create next app",
};

const AdminLayout = ({children}) => {
  return (
    <>
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <p className="ml-5">Admin Layout</p>
        {children}
      </body>
      </html>
    </>
  )
};
export default AdminLayout;